#! Test pipeline used when ootb-supply-chain-testing or ootb-supply-chain-testing-scanning is enabled.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline-java
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: java
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
spec:
  params:
  - name: source-url
  - name: source-revision
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
      - name: test
        image: gradle
        script: |-
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m
          pwd
          MVNW=mvnw
          GRADLE="build.gradle"
          if [ -f "$MVNW" ]; then
              ./mvnw test
          elif [ -f "$GRADLE" ]; then
              gradle test --debug
          else
              echo "WARNING: No tests were run. This workload is not built with one of the currently supported frameworks (maven or gradle). If using another language/framework, update the image and the script sections of the 'pipeline.tekton.dev' resource in your namespace to match your language/framework."
              #exit 1
          fi
        volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
      sidecars:
      - image: docker:dind
        name: docker
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
      volumes:
      - name: dind-socket
        emptyDir: {}