tap_install:
    sensitive_values:
        tap_gui:
            app_config:
                auth:
                    providers:
                        github:
                            development:
                                clientId: ENC[AES256_GCM,data:l66YBvjJLBnk0kfLwD8nFBR/vMs=,iv:6rcNNnokwbEPqkG+Avv16kqJXG5M1WNdb58MOuSA3Bs=,tag:IhyFbKPiKIs8n2MkyZMC0A==,type:str]
                                clientSecret: ENC[AES256_GCM,data:ZupWDNYO4VMkhu+qCDwKl8vJa+SQtGPw0l3kKP8Iv9hFzHSRuGFEDw==,iv:RifPKOeZ8hZoCgJfbuxW+Em5jZlzxgunXo7wOoeJOek=,tag:Kb4RZLpQO11BTKtiChy0Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ccghc7r0nczmrs6dkfe0vltjgkwpjcvykqd9m9f4xm532dc3ecpsfn3scw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOU9yaFN2VUhVME5vOTRQ
            OGJYWVJNVldXK2tQeU9LazlmM3B4cnJGbjBzCnJtb1p1Rm1IUVFqUEpxanEzMjVr
            b1JlVTNLY3k1S2o5YS9rRVhDRm5ZbzgKLS0tIGJpVC9jRzNSK00wRkU2WWoxZnh4
            RGl5ZVgzSU8zRXo2UWZzMS81NXViR1kKv8sa1zayPgczJ3vaDuOlLlQsO6pUYzBY
            sxsq2vaWvwrz+fYu+5gQV6sMeFwLDBFylX0TwcUJh9N0/EF9Kt8CGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T16:42:09Z"
    mac: ENC[AES256_GCM,data:KvB4m2NhDWBme7V5eNmv58sbOcH9Cd6dzHEoUTBbS/YWR/g9fxvvQfLS7LFGlET7wquPLcPHj8AsphNFhRQ6lqADSNOmfxsd0hrEGUFYuYqi96LZ1T+BqY3V8FlBfooYmv03E9SAAB49u0tNoQpOfKKZUD8SuGkEF5aSIg+fgwA=,iv:a9HDapB8TwW9upta4KKkVFIcsuY7vfVaAiMdKjuEeM0=,tag:++upbjRDol9l5wdcQ6ErWQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
