tap_install:
  values:
    shared:
      # ingressEnabled: true
      ingress_domain: tap.robertocolella.com
      ingress_issuer: letsencrypt-contour-cluster-issuer
      image_registry:
        project_path: colellar.azurecr.io/tap
    
      kubernetes_version: "1.27"

    ceip_policy_disclosed: true
    profile: full

    supply_chain: basic #testing_scanning 
    ootb_supply_chain_basic:
      registry:
        server: colellar.azurecr.io
        repository: tap/supplychain
      gitops:
        ssh_secret: git-secret
    ootb_supply_chain_testing:
      registry:
        server: colellar.azurecr.io
        repository: tap/supplychain
      gitops:
        ssh_secret: git-secret
    ootb_supply_chain_testing_scanning:
      registry:
        server: colellar.azurecr.io
        repository: tap/supplychain
      gitops:
        server_address: https://github.com/
        repository_owner: robertocolella
        repository_name: tap-gitops-config-delivery
        branch: main
        ssh_secret: git-secret
        commit_strategy: pull_request
        pull_request:
          server_kind: github
          commit_branch: ""
          pull_request_title: ready for review
          pull_request_body: generated by supply chain
        # ## TEST GITOPS WORKLOAD
        # ssh_secret: git-secret
        # server_address: https://github.com/
        # repository_owner: robertocolella
        # repository_name: tapqs-gitops

    contour:
      envoy:
        service:
          type: LoadBalancer

    buildservice:
      kp_default_repository: colellar.azurecr.io/tap/build-service
      kp_default_repository_username: colellar
      # exclude_dependencies: true
 
    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      app_config:
        app: 
          baseUrl: https://tap-gui.tap.robertocolella.com
        integrations:
          github:
            - host: github.com
        auth:
          environment: development
          allowGuestAccess: true
          loginPage:
            github:
              title: Github Login
              message: Enter with your GitHub account
          backend:
          baseUrl: https://tap-gui.tap.robertocolella.com # No port needed with Ingress
          cors:
            origin: https://tap-gui.tap.robertocolella.com # No port needed with Ingress
        organization:
          name: 'Customer Platform Team'    
        customize:
          # custom_logo: ""
          custom_name: "Tanzu Application Platform"
          banners:
            text: "Test Environment"
            color: "#ffffff"
            bg: "#007a33"
            link: "https://tanzu.vmware.com/application-platform"
        catalog:
          locations:
          - type: url
            target: https://github.com/MoSehsah/bank-demo/blob/main/catalog/catalog-info.yaml

    accelerator:
      managed_resources:
        git:
          url: https://github.com/robertocolella/tap-accelerators
          ref: origin/main
          sub_path: resources
          secret_ref: null
        enable: true

    cnrs:
      domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
      ingress_issuer: letsencrypt-contour-cluster-issuer
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
    scanning:
      # metadataStore:
      #   url: ""
    grype:
      namespace: "default"
      # targetImagePullSecret: scanner-secret-ref
      targetImagePullSecret: registries-credentials
    policy:
      tuf_enabled: false

    springboot_conventions:
      autoConfigureActuators: true
    
    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    appliveview_connector:
      activateSensitiveOperations: true  

    local_source_proxy:
      repository: colellar.azurecr.io/tap-lsp/tap-lsp
      push_secret:
        name: registries-credentials
        namespace: default
        create_export: true
      pull_secret:
        name: registries-credentials
        namespace: default
        create_export: true

    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: namespace-provisioner/namespaces
        url: https://github.com/robertocolella/tap-gitops.git
      additional_sources:
      - git:
          ref: origin/main
          subPath: namespace-provisioner/resources
          url: https://github.com/robertocolella/tap-gitops.git
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git-secret