tap_install:
  values:
    shared:
      ingress_domain: tap.robertocolella.com
      image_registry:
        project_path: harbor.dorn.tkg-azure-lab.robertocolella.com/tap
    ceip_policy_disclosed: true
    profile: full
    supply_chain: testing_scanning
    ootb_supply_chain_basic:
      registry:
        server: harbor.dorn.tkg-azure-lab.robertocolella.com
        repository: tap/supplychain
      gitops:
        ssh_secret: ""
    ootb_supply_chain_testing:
      registry:
        server: harbor.dorn.tkg-azure-lab.robertocolella.com
        repository: tap/supplychain
      gitops:
        ssh_secret: ""
    ootb_supply_chain_testing_scanning:
      registry:
        server: harbor.dorn.tkg-azure-lab.robertocolella.com
        repository: tap/supplychain
      gitops:
        ssh_secret: ""
    contour:
      envoy:
        service:
          type: LoadBalancer
    buildservice:
      kp_default_repository: harbor.dorn.tkg-azure-lab.robertocolella.com/tap/build-service
      kp_default_repository_username: admin
    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      app_config:
        customize:
          custom_logo: PGh0bWwgbGFuZz0iZGUiPjxoZWFkPjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0idGV4dC9odG1sOyBjaGFyc2V0PUlTTy04ODU5LTEiPjx0aXRsZT5XZWl0ZXJsZWl0dW5nc2hpbndlaXM8L3RpdGxlPjxzdHlsZT5ib2R5LGRpdixhe2ZvbnQtZmFtaWx5OmFyaWFsLHNhbnMtc2VyaWZ9Ym9keXtiYWNrZ3JvdW5kLWNvbG9yOiNmZmY7bWFyZ2luLXRvcDozcHh9ZGl2e2NvbG9yOiMwMDB9YTpsaW5re2NvbG9yOiM0YjExYTg7fWE6dmlzaXRlZHtjb2xvcjojNGIxMWE4O31hOmFjdGl2ZXtjb2xvcjojZWE0MzM1fWRpdi5teW1Hb3tib3JkZXItdG9wOjFweCBzb2xpZCAjZGFkY2UwO2JvcmRlci1ib3R0b206MXB4IHNvbGlkICNkYWRjZTA7YmFja2dyb3VuZDojZjhmOWZhO21hcmdpbi10b3A6MWVtO3dpZHRoOjEwMCV9ZGl2LmFYZ2FHYntwYWRkaW5nOjAuNWVtIDA7bWFyZ2luLWxlZnQ6MTBweH1kaXYuZlRrN3Zke21hcmdpbi1sZWZ0OjM1cHg7bWFyZ2luLXRvcDozNXB4fTwvc3R5bGU+PC9oZWFkPjxib2R5PjxkaXYgY2xhc3M9Im15bUdvIj48ZGl2IGNsYXNzPSJhWGdhR2IiPjxmb250IHN0eWxlPSJmb250LXNpemU6bGFyZ2VyIj48Yj5XZWl0ZXJsZWl0dW5nc2hpbndlaXM8L2I+PC9mb250PjwvZGl2PjwvZGl2PjxkaXYgY2xhc3M9ImZUazd2ZCI+Jm5ic3A7RGllIHZvbiBkaXIgYmVzdWNodGUgU2VpdGUgdmVyc3VjaHQsIGRpY2ggYW4gPGEgaHJlZj0iaHR0cHM6Ly9pY29uczguaXQvaWNvbi8xZUdlaWt4OUJ6VHcvYmFieS15b2RhIj5odHRwczovL2ljb25zOC5pdC9pY29uLzFlR2Vpa3g5QnpUdy9iYWJ5LXlvZGE8L2E+IHdlaXRlcnp1bGVpdGVuLjxicj48YnI+Jm5ic3A7RmFsbHMgZHUgZGllc2UgU2VpdGUgbmljaHQgYmVzdWNoZW4gbfZjaHRlc3QsIGthbm5zdCBkdSA8YSBocmVmPSIjIiBpZD0idHN1aWRfMSI+enVyIHZvcmhlcmlnZW4gU2VpdGUgenVy/GNra2VocmVuPC9hPi48c2NyaXB0IG5vbmNlPSJQaGg4MWZPYjIycE96ZmxTYlhGV2ZBIj4oZnVuY3Rpb24oKXt2YXIgaWQ9J3RzdWlkXzEnOyhmdW5jdGlvbigpe2RvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlkKS5vbmNsaWNrPWZ1bmN0aW9uKCl7d2luZG93Lmhpc3RvcnkuYmFjaygpO3JldHVybiExfTt9KS5jYWxsKHRoaXMpO30pKCk7KGZ1bmN0aW9uKCl7dmFyIGlkPSd0c3VpZF8xJzt2YXIgY3Q9J29yaWdpbmxpbmsnO3ZhciBvaT0ndW5hdXRob3JpemVkcmVkaXJlY3QnOyhmdW5jdGlvbigpe2RvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlkKS5vbm1vdXNlZG93bj1mdW5jdGlvbigpe3ZhciBiPWRvY3VtZW50JiZkb2N1bWVudC5yZWZlcnJlcixhPSJlbmNvZGVVUklDb21wb25lbnQiaW4gd2luZG93P2VuY29kZVVSSUNvbXBvbmVudDplc2NhcGUsYz0iIjtiJiYoYz1hKGIpKTsobmV3IEltYWdlKS5zcmM9Ii91cmw/c2E9VCZ1cmw9IitjKyImb2k9IithKG9pKSsiJmN0PSIrYShjdCk7cmV0dXJuITF9O30pLmNhbGwodGhpcyk7fSkoKTs8L3NjcmlwdD48YnI+PGJyPjxicj48L2Rpdj48L2JvZHk+PC9odG1sPg==  
          custom_name: 'Roberto Colella - Tanzu Application Platform'
        catalog:
          locations:
          - type: url
            target: https://github.com/MoSehsah/bank-demo/blob/main/catalog/catalog-info.yaml
    cnrs:
      domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
    scanning:
      metadataStore:
        url: ""
    grype:
      namespace: my-apps
      targetImagePullSecret: tap-registry
    policy:
      tuf_enabled: false
    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    appliveview_connector:
      activateSensitiveOperations: true  