tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:0Rwno/A2ey2C0qjMHDSPktdF8kjhcU08ss+cTwE4yaWLpYuAf3YcxUYefRbhVyJ6,iv:cY7Yq1H8yOhiqGqWziphSdsOVeuXPSJsECR0nzDnNRw=,tag:ZBP5GJdzX/SmSZJ3lMDpRg==,type:str]
                username: ENC[AES256_GCM,data:nErEM82tCXEczQuUWkny9lQV6mg=,iv:3VUgY4iNMPesboRWYZZSL/KLEzxYNMyYT3spBWRSFas=,tag:UKlyTPKWOpYcbJYRlCItng==,type:str]
                password: ENC[AES256_GCM,data:5pkVJ2fb4+szu5BlQIaH+clZQTQWgMNJDezNL5KyIAE=,iv:dltCHTSeN6E152GLOheTfNfmrcGwNOCfDSa3FSuZezQ=,tag:qr+K8OKvqwurCKc+pD//Dw==,type:str]
        buildservice:
            kp_default_repository_password: ENC[AES256_GCM,data:7OsW/Y5mRsU=,iv:UR5fp60p5ym9G8y8wRUEiPf/xxCdjDGUH/qW8hA2z9k=,tag:9UaR3P260vwa++aQlMfEyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ccghc7r0nczmrs6dkfe0vltjgkwpjcvykqd9m9f4xm532dc3ecpsfn3scw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSkt3bmgrQ1JKZCtMYy9N
            R3kzU3ZWZ2tOdGhmc0Y5dW0zOEpKLzJyS2tNCldFTDd0ZnQyUkNzN2dpUjU1a095
            bnA3anRwSWhlWkhmYVhLRlh0YXF2TWcKLS0tIGxKWTlEa1c2WlVURzR6Ym45dFpP
            QzlBYkUxcEVuZHBIa3RYc3kxb01lZ3cK9k9KalhHZvDgRc15KDSrL4ov6fTmKKkD
            hI7MqyAS60z8e5cZPe+8SHemz41veWj1cFO8xRYjsc0pG2Vtqlja+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T14:11:46Z"
    mac: ENC[AES256_GCM,data:nET9WKI5OMrzDqBkiGoqSKThSqujunxBGjbRJlJUGtM2BbWNdaqSLssDh82lt5ObTudKqn08BJZi8e34IHjlK4KbDaw4gLKiNyXNL1C0Sp4YsgT2oTS6VFiAjoAfUvPLXGIiTxVRBDr++BbK5k3aEGMrB09MrFTQdnKt8evBwgc=,iv:J7+5qW0rpCtLpBsFjPWLglAJomjUctRGAcnbkwtxlgE=,tag:2I1qjkUiIUOtkGbn4+IJBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
