apiVersion: ENC[AES256_GCM,data:J/A=,iv:YXa6LlAtvnsoTmHssHpWFc2V74Yo9ViJiYYQfCNb8Xo=,tag:PLp5hUVSc0kdrB/w65t2rg==,type:str]
kind: ENC[AES256_GCM,data:joAO8Q61,iv:YpbouH63XgoFWlljDHqkW1eT/Jb9bHCTanjfH5fv8wc=,tag:r+B17xh4SEHo5DzAyEKtwA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PGk/9W3Zt7h//Q==,iv:1tarUx1G1DH7iKr84tcEDFLtHOyueM4rVqX7ZvQ+01A=,tag:w0GZbOKuHWVIZgZ/rcxsQg==,type:str]
    namespace: ENC[AES256_GCM,data:lUjb6urRPg6/+y4=,iv:Px/x4YBTuZVVaLyaPlpTbrTqPS7DhM955FJNxpHZ7Ww=,tag:dX9SYf9dnM3LLjEZgEmpHA==,type:str]
    annotations:
        tekton.dev/git-0: ENC[AES256_GCM,data:rGiaTv0k9XB3Lfeabn1+MF/4,iv:xjPkt+YA5myt1jk62uwPctcSY6lJNS5t5KCZW1fl1Zc=,tag:HquubjxP2o88aUBu6C/csg==,type:str]
type: ENC[AES256_GCM,data:0VGhVkaaT5Fn3h7Zeukfm68fNoCNCxpL,iv:O4zGEKxGBrEw0Mw3uKP2GI31BHyBZ0X+lIOiiA0AkxQ=,tag:mNavP48d2f3imByFX4evrg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:lvOw3Icw6tqdoc3Jgsg=,iv:6fUukn46Juqr37GHqtJkDpkx1iPsaaevg/dXonvsBlg=,tag:jTYR86UomSc+mWSMKifNUg==,type:str]
    #ENC[AES256_GCM,data:BYXt5Ut/VqnUl1+c7oHZJo7SnDnmBixw8lS/Kx5PJ5RuAtRtGDjiO0Yo9AkcYibwcezj,iv:jN1Gfp0ey2DKCQ0wa8q+vXuIwmaz/3/XdGrPeexoZ0c=,tag:oIEaY4wdwcxgr8VgnVG4ow==,type:comment]
    password: ENC[AES256_GCM,data:s33O5SymzOLVJXfLnWFckUUiCAgSW6HZjZ4Ni8kVXMTppJOlZO1RCw==,iv:afzUOO+aggeD4HBLili7FHIGvo1ltk57+89QdbKB/e8=,tag:/u4f4xH95hYIvDI7SYi3jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ccghc7r0nczmrs6dkfe0vltjgkwpjcvykqd9m9f4xm532dc3ecpsfn3scw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2a0R4d29pdkZRbUpZdGRq
            VXo4MVFsRnN2eWo0b2pHcnlrMnFCMjZscHhJCm5FTGQxS3RTK1ZURlBVWmhhaWgr
            NmRLQnpKdTJkbzgxNjN1emtmZ29YdUEKLS0tIFp6bmxQV0NXSG5GcWx0OE4vV2t2
            MkcwaHAvTUFFTTdURVRCYko4K1J5R2sKHF8Z9QesSM28bTbp72dpML+1ylP9m/RU
            l0djaNY2gYc4ENCDbODXi8Yl/McVLvRvI2kfsTWYstD86O9Y4d+EGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T21:13:37Z"
    mac: ENC[AES256_GCM,data:UnM45Rgsw9jh1aw09IeyJyEpmZX9np2/vkDH3W7Xm6B4Pw3u6rXZ1CGPYZ3pUdWmioGeldpXJE3FiUhTL5RlKO2S+D+9NMe/tewYhXgz1X6Ew2VjH5KUIZms9i/qG6h9shJql2KvYoEPzKfaAVSwmBA7TRBidCnwS4vSpCeOtCI=,iv:uiXYCamd8B26SD1CkO4ADji6u63RO7UIRn7AIpQkXME=,tag:mfDo8n4cFWnnF6FFGBOXkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
